name:  Test-math

on:
  push:
    branches: [ main ]

jobs:
        
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
        - run: echo Testando calculos
      
  deploy-main:
    name: Teste em main
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      # Install required deps for action - jest, jest-html-report
      - name: Install Dependencies
        run: npm install --save-dev jest jest-html-reporter 

      # Finally, run our tests
      - name: Run the tests
        run: npm test
        
      - name: Generate report
        run:  npm test
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: jest-report
          path: './test-report.html'
      - run: echo REALIZANDO TESTES UNITARIOS
      
  
